# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import payment_callback_pb2 as payment__callback__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in payment_callback_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PaymentCallbackStub(object):
    """Service for receiving payment callbacks.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessPaymentCallback = channel.unary_unary(
                '/wallet.PaymentCallback/ProcessPaymentCallback',
                request_serializer=payment__callback__pb2.TransactionRequest.SerializeToString,
                response_deserializer=payment__callback__pb2.TransactionResponse.FromString,
                _registered_method=True)


class PaymentCallbackServicer(object):
    """Service for receiving payment callbacks.
    """

    def ProcessPaymentCallback(self, request, context):
        """RPC method that PaymentGatewayService will call to send back transaction data.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PaymentCallbackServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessPaymentCallback': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessPaymentCallback,
                    request_deserializer=payment__callback__pb2.TransactionRequest.FromString,
                    response_serializer=payment__callback__pb2.TransactionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'wallet.PaymentCallback', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('wallet.PaymentCallback', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PaymentCallback(object):
    """Service for receiving payment callbacks.
    """

    @staticmethod
    def ProcessPaymentCallback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wallet.PaymentCallback/ProcessPaymentCallback',
            payment__callback__pb2.TransactionRequest.SerializeToString,
            payment__callback__pb2.TransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
