# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: payment_callback.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'payment_callback.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16payment_callback.proto\x12\x06wallet\"\x90\x01\n\x12TransactionRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\x05\x12\x13\n\x0bwallet_uuid\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x03\x12\x18\n\x10transaction_type\x18\x04 \x01(\t\x12\x0e\n\x06status\x18\x05 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x06 \x01(\t\"6\n\x13TransactionResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2d\n\x0fPaymentCallback\x12Q\n\x16ProcessPaymentCallback\x12\x1a.wallet.TransactionRequest\x1a\x1b.wallet.TransactionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payment_callback_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSACTIONREQUEST']._serialized_start=35
  _globals['_TRANSACTIONREQUEST']._serialized_end=179
  _globals['_TRANSACTIONRESPONSE']._serialized_start=181
  _globals['_TRANSACTIONRESPONSE']._serialized_end=235
  _globals['_PAYMENTCALLBACK']._serialized_start=237
  _globals['_PAYMENTCALLBACK']._serialized_end=337
# @@protoc_insertion_point(module_scope)
