# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: refund_gateway.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'refund_gateway.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14refund_gateway.proto\x12\x06refund\"\x8b\x01\n\rRefundRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\x05\x12\x13\n\x0bwallet_uuid\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x03\x12\x18\n\x10transaction_type\x18\x04 \x01(\t\x12\x0e\n\x06status\x18\x05 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x06 \x01(\t\"1\n\x0eRefundResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2O\n\rRefundGateway\x12>\n\rProcessRefund\x12\x15.refund.RefundRequest\x1a\x16.refund.RefundResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'refund_gateway_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REFUNDREQUEST']._serialized_start=33
  _globals['_REFUNDREQUEST']._serialized_end=172
  _globals['_REFUNDRESPONSE']._serialized_start=174
  _globals['_REFUNDRESPONSE']._serialized_end=223
  _globals['_REFUNDGATEWAY']._serialized_start=225
  _globals['_REFUNDGATEWAY']._serialized_end=304
# @@protoc_insertion_point(module_scope)
