# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import user_event_pb2 as user__event__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in user_event_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UserEventServiceStub(object):
    """Service for handling user events.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateUserEvent = channel.unary_unary(
                '/wallet_service.UserEventService/CreateUserEvent',
                request_serializer=user__event__pb2.CreateUserEventRequest.SerializeToString,
                response_deserializer=user__event__pb2.CreateUserEventResponse.FromString,
                _registered_method=True)


class UserEventServiceServicer(object):
    """Service for handling user events.
    """

    def CreateUserEvent(self, request, context):
        """RPC method for creating a user event.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserEventServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateUserEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUserEvent,
                    request_deserializer=user__event__pb2.CreateUserEventRequest.FromString,
                    response_serializer=user__event__pb2.CreateUserEventResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'wallet_service.UserEventService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('wallet_service.UserEventService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserEventService(object):
    """Service for handling user events.
    """

    @staticmethod
    def CreateUserEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wallet_service.UserEventService/CreateUserEvent',
            user__event__pb2.CreateUserEventRequest.SerializeToString,
            user__event__pb2.CreateUserEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
