# Generated by Django 5.1.5 on 2025-02-02 12:37

import Wallet.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='wallet_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[(Wallet.models.TransactionType['CREDIT'], 'credit'), (Wallet.models.TransactionType['DEBIT'], 'debit')], default='credit', max_length=50),
        ),
    ]
