# Generated by Django 5.1.5 on 2025-02-03 04:49

import Wallet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0002_wallet_wallet_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[(Wallet.models.TransactionStatus['PENDING'], 'pending'), (Wallet.models.TransactionStatus['COMPLETED'], 'completed'), (Wallet.models.TransactionStatus['FAILED'], 'failed')], default='pending', max_length=50),
        ),
    ]
